- name: set hostname
  hostname: name=virtual-{{ ansible_distribution }}-worker{{ (ansible_all_ipv4_addresses | join(' ') | regex_search('\\b192\\.(?:[0-9]{1,3}\\.){2}[0-9]{1,3}\\b')).split('.')[-1] }}
