---
- hosts: worker
  vars:
    remorte_user: root

  tasks:
    - name: show hostname
      shell: hostname
      register: get_hostname
    - name: debug hostname
      debug:
        msg: "{{ get_hostname.stdout }}"

    - name: debug ip
      debug:
        msg: "{{ ansible_all_ipv4_addresses }}"

    - name: debug ip2
      debug:
        msg: "{{ ansible_all_ipv4_addresses | join(' ') | regex_search('\\b192\\.(?:[0-9]{1,3}\\.){2}[0-9]{1,3}\\b') }}"
        # msg: "{{ ansible_all_ipv4_addresses | join(' ') | regex_findall('\\b192\\.(?:[0-9]{1,3}\\.){2}[0-9]{1,3}\\b') }}"
        # msg: "{{ ansible_all_ipv4_addresses | join(' ') | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

    - name: set hostname
      hostname: name=virtual-{{ ansible_distribution }}-worker{{ (ansible_all_ipv4_addresses | join(' ') | regex_search('\\b192\\.(?:[0-9]{1,3}\\.){2}[0-9]{1,3}\\b')).split('.')[-1] }}
