---
- hosts: all
  vars_files:
    - ../../../automatic.yml
  tasks:
    - name: check necessary rpm packages is ready
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - libaio
        - zlib
        - sqlite
        - sqlite-devel
        - bc
      ignore_errors: yes

    - name: check necessary pip3 packages is ready
      pip:
        name: "{{ item }}"
        executable: pip3
      with_items:
        - sqlalchemy
        - pyyaml
      ignore_errors: yes

    - name: check unnecessary rpm packages is ready
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - zip
        - unzip
        - telnet
        - net-tools
      ignore_errors: yes

