---
  - hosts: worker,base
    user: root
    tasks:
     - name: ssh-copy
       authorized_key: user=root key="{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
       tags:
         - sshkey
